/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Ratnadip
 */
public class AdminRegistration extends javax.swing.JFrame {
java.sql.Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    /**
     * Creates new form AdminRegistration
     */
    public AdminRegistration() {
        initComponents();
        conn = Dbconnect.ConnectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Usernamelbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstnametext = new javax.swing.JTextField();
        lastnametext = new javax.swing.JTextField();
        usernametext = new javax.swing.JTextField();
        passwordtext = new javax.swing.JTextField();
        RegisterAdminbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText(" Beer & wine Shopee");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 94, 458, 50);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Admin Registration");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(634, 180, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(580, 244, 90, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(580, 310, 83, 22);

        Usernamelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Usernamelbl.setText("Username");
        getContentPane().add(Usernamelbl);
        Usernamelbl.setBounds(580, 360, 78, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(580, 420, 90, 30);
        getContentPane().add(firstnametext);
        firstnametext.setBounds(720, 240, 170, 30);
        getContentPane().add(lastnametext);
        lastnametext.setBounds(720, 300, 170, 30);
        getContentPane().add(usernametext);
        usernametext.setBounds(720, 360, 170, 30);
        getContentPane().add(passwordtext);
        passwordtext.setBounds(720, 420, 170, 30);

        RegisterAdminbtn.setBackground(new java.awt.Color(51, 204, 0));
        RegisterAdminbtn.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        RegisterAdminbtn.setText("Register Admin");
        RegisterAdminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterAdminbtnActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterAdminbtn);
        RegisterAdminbtn.setBounds(670, 500, 180, 35);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Images/corona-extra-beer-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1810, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterAdminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterAdminbtnActionPerformed
        // TODO add your handling code here:
        /* try{
             String sql = "insert into ADMIN (FIRSTNAME,LASTNAME,USERNAME,PASSWORD) VALUES(?,?,?,?)";
             pst=(OraclePreparedStatement)conn.prepareStatement(sql);
             pst.setString(1,firstnametext.getText());
             pst.setString(2, lastnametext.getText());
             pst.setString(3,usernametext.getText());
             pst.setString(4,passwordtext.getText());
             rs=(OracleResultSet) pst.executeQuery(sql);
         }
         catch(SQLException e){
             JOptionPane.showMessageDialog(null,e);
             e.printStackTrace();
         }*/
        try {
            String sql = "Insert into ADMIN (FIRSTNAME,LASTNAME,USERNAME,PASSWORD) values (?,?,?,?)";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, firstnametext.getText());

            pst.setString(2, lastnametext.getText());
            pst.setString(3, usernametext.getText());

            pst.setString(4, passwordtext.getText());
            
            rs = (OracleResultSet) pst.executeQuery();
            JOptionPane.showMessageDialog(null, "Saved");
            
             AdminLogin AL = new AdminLogin();
            AL.setVisible(true);
            this.setVisible(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();
        }
    }//GEN-LAST:event_RegisterAdminbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterAdminbtn;
    private javax.swing.JLabel Usernamelbl;
    private javax.swing.JTextField firstnametext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lastnametext;
    private javax.swing.JTextField passwordtext;
    private javax.swing.JTextField usernametext;
    // End of variables declaration//GEN-END:variables
}
