/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

/**
 *
 * @author Ratnadip
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form Sales
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AdminMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AddNewWaiter = new javax.swing.JMenuItem();
        ViewWaiter = new javax.swing.JMenuItem();
        PaymentWaiter = new javax.swing.JMenuItem();
        UpdateWaiter = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AddNewVehicle = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        ViewVehicleDetails = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AddNewPurchase = new javax.swing.JMenuItem();
        ViewPurchase = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        AddNewStorage = new javax.swing.JMenuItem();
        UpdateStorage = new javax.swing.JMenuItem();
        ViewStorage = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        AddNewCustomer = new javax.swing.JMenuItem();
        ViewCustomer = new javax.swing.JMenuItem();
        UpdateCustomer = new javax.swing.JMenuItem();
        DeleteCustomer = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        NewSaleEntry = new javax.swing.JMenuItem();
        ViewSale = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        ViewReport = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        Contact = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText(" Beer & Wine Shopee");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 80, 660, 66);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Images/heineken_beer1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1490, 768);

        AdminMenuBar.setBackground(new java.awt.Color(51, 51, 0));
        AdminMenuBar.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jMenu1.setText("Waiter");

        AddNewWaiter.setText("Add New Waiter");
        AddNewWaiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewWaiterActionPerformed(evt);
            }
        });
        jMenu1.add(AddNewWaiter);

        ViewWaiter.setText("View Waiter");
        jMenu1.add(ViewWaiter);

        PaymentWaiter.setText("Make Payment");
        PaymentWaiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentWaiterActionPerformed(evt);
            }
        });
        jMenu1.add(PaymentWaiter);

        UpdateWaiter.setText("Update Waiter");
        UpdateWaiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateWaiterActionPerformed(evt);
            }
        });
        jMenu1.add(UpdateWaiter);

        AdminMenuBar.add(jMenu1);

        jMenu2.setText("Transport Vehicle");

        AddNewVehicle.setText("Add New Vahicle");
        AddNewVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewVehicleActionPerformed(evt);
            }
        });
        jMenu2.add(AddNewVehicle);

        jMenuItem6.setText("Update Transport");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        ViewVehicleDetails.setText("View Details");
        ViewVehicleDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewVehicleDetailsActionPerformed(evt);
            }
        });
        jMenu2.add(ViewVehicleDetails);

        AdminMenuBar.add(jMenu2);

        jMenu3.setText("Purchase");

        AddNewPurchase.setText("Add New");
        AddNewPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewPurchaseActionPerformed(evt);
            }
        });
        jMenu3.add(AddNewPurchase);

        ViewPurchase.setText("View Purchase");
        ViewPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPurchaseActionPerformed(evt);
            }
        });
        jMenu3.add(ViewPurchase);

        AdminMenuBar.add(jMenu3);

        jMenu4.setText("Storage");

        AddNewStorage.setText("Add Storage");
        AddNewStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewStorageActionPerformed(evt);
            }
        });
        jMenu4.add(AddNewStorage);

        UpdateStorage.setText("Update Storage");
        UpdateStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStorageActionPerformed(evt);
            }
        });
        jMenu4.add(UpdateStorage);

        ViewStorage.setText("View Storage");
        ViewStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStorageActionPerformed(evt);
            }
        });
        jMenu4.add(ViewStorage);

        AdminMenuBar.add(jMenu4);

        jMenu5.setText("Customer");

        AddNewCustomer.setText("Add New Customer");
        AddNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewCustomerActionPerformed(evt);
            }
        });
        jMenu5.add(AddNewCustomer);

        ViewCustomer.setText("View Customer");
        ViewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCustomerActionPerformed(evt);
            }
        });
        jMenu5.add(ViewCustomer);

        UpdateCustomer.setText("Update Customer");
        UpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCustomerActionPerformed(evt);
            }
        });
        jMenu5.add(UpdateCustomer);

        DeleteCustomer.setText("Delete Customer");
        DeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCustomerActionPerformed(evt);
            }
        });
        jMenu5.add(DeleteCustomer);

        AdminMenuBar.add(jMenu5);

        jMenu6.setText("Sales");

        NewSaleEntry.setText("Add New Sale Entry");
        NewSaleEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSaleEntryActionPerformed(evt);
            }
        });
        jMenu6.add(NewSaleEntry);

        ViewSale.setText("View Sale");
        ViewSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSaleActionPerformed(evt);
            }
        });
        jMenu6.add(ViewSale);

        AdminMenuBar.add(jMenu6);

        jMenu7.setText("Report");

        ViewReport.setText("View Report");
        ViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewReportActionPerformed(evt);
            }
        });
        jMenu7.add(ViewReport);

        AdminMenuBar.add(jMenu7);

        jMenu8.setText("About");

        Contact.setBackground(new java.awt.Color(51, 51, 0));
        Contact.setText("Contact");
        jMenu8.add(Contact);

        AdminMenuBar.add(jMenu8);

        setJMenuBar(AdminMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewWaiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewWaiterActionPerformed
        // TODO add your handling code here:
        WaiterRegistration WR = new WaiterRegistration();
        WR.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddNewWaiterActionPerformed

    private void UpdateWaiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateWaiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateWaiterActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        UpdateTransport UT = new UpdateTransport();
        UT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void ViewPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPurchaseActionPerformed
        // TODO add your handling code here:
        ViewPurchase VP = new ViewPurchase();
        VP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewPurchaseActionPerformed

    private void AddNewStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewStorageActionPerformed
        // TODO add your handling code here:
        AddStorage AS = new AddStorage();
        AS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddNewStorageActionPerformed

    private void ViewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCustomerActionPerformed
        // TODO add your handling code here:
        ViewCustomer VC = new ViewCustomer();
        VC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewCustomerActionPerformed

    private void UpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCustomerActionPerformed
        // TODO add your handling code here:
         UpdateCustomer UC = new UpdateCustomer();
        UC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UpdateCustomerActionPerformed

    private void PaymentWaiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentWaiterActionPerformed
        // TODO add your handling code here:
        WorkerPayment WP = new WorkerPayment();
        WP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PaymentWaiterActionPerformed

    private void AddNewVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewVehicleActionPerformed
        // TODO add your handling code here:
        TransportVehicle TV= new TransportVehicle();
        TV.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddNewVehicleActionPerformed

    private void ViewVehicleDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewVehicleDetailsActionPerformed
        // TODO add your handling code here:
         ViewTransport VT = new ViewTransport();
        VT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewVehicleDetailsActionPerformed

    private void AddNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewCustomerActionPerformed
        // TODO add your handling code here:
        Customer cust = new Customer();
        cust.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddNewCustomerActionPerformed

    private void DeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCustomerActionPerformed
        // TODO add your handling code here:
        DeleteCustomer DC = new DeleteCustomer();
        DC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DeleteCustomerActionPerformed

    private void AddNewPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewPurchaseActionPerformed
        // TODO add your handling code here:
        Purchase purchase = new Purchase();
        purchase.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddNewPurchaseActionPerformed

    private void UpdateStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStorageActionPerformed
        // TODO add your handling code here:
        UpdateStorage US = new UpdateStorage();
        US.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UpdateStorageActionPerformed

    private void ViewStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStorageActionPerformed
            ViewStorage VS = new ViewStorage();
            VS.setVisible(true);
            this.setVisible(false); 
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewStorageActionPerformed

    private void NewSaleEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSaleEntryActionPerformed
        // TODO add your handling code here:
        Sale sale=new Sale();
        sale.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NewSaleEntryActionPerformed

    private void ViewSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSaleActionPerformed
        // TODO add your handling code here:
        ViewSale VS=new ViewSale();
        VS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewSaleActionPerformed

    private void ViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewReportActionPerformed
        // TODO add your handling code here:
        ViewReport VR= new ViewReport();
        VR.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddNewCustomer;
    private javax.swing.JMenuItem AddNewPurchase;
    private javax.swing.JMenuItem AddNewStorage;
    private javax.swing.JMenuItem AddNewVehicle;
    private javax.swing.JMenuItem AddNewWaiter;
    private javax.swing.JMenuBar AdminMenuBar;
    private javax.swing.JMenuItem Contact;
    private javax.swing.JMenuItem DeleteCustomer;
    private javax.swing.JMenuItem NewSaleEntry;
    private javax.swing.JMenuItem PaymentWaiter;
    private javax.swing.JMenuItem UpdateCustomer;
    private javax.swing.JMenuItem UpdateStorage;
    private javax.swing.JMenuItem UpdateWaiter;
    private javax.swing.JMenuItem ViewCustomer;
    private javax.swing.JMenuItem ViewPurchase;
    private javax.swing.JMenuItem ViewReport;
    private javax.swing.JMenuItem ViewSale;
    private javax.swing.JMenuItem ViewStorage;
    private javax.swing.JMenuItem ViewVehicleDetails;
    private javax.swing.JMenuItem ViewWaiter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
