/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Ratnadip
 */
public class Customer extends javax.swing.JFrame {
java.sql.Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
 
    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
                                conn = Dbconnect.ConnectDb();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        licencenumber = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        view = new javax.swing.JButton();
        update = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText(" Beer & Wine Shopee");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 40, 670, 60);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel2.setText("Customer Registration");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 110, 240, 30);

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel3.setText("Licence Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 160, 120, 20);

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel4.setText("First name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(440, 230, 120, 20);

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(440, 310, 120, 20);

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 390, 120, 20);
        getContentPane().add(licencenumber);
        licencenumber.setBounds(590, 160, 140, 30);
        getContentPane().add(firstname);
        firstname.setBounds(590, 230, 140, 30);
        getContentPane().add(lastname);
        lastname.setBounds(590, 310, 140, 30);
        getContentPane().add(address);
        address.setBounds(590, 390, 140, 30);

        save.setBackground(new java.awt.Color(0, 204, 0));
        save.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(330, 500, 80, 31);

        view.setBackground(new java.awt.Color(255, 255, 0));
        view.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view);
        view.setBounds(470, 500, 80, 31);

        update.setBackground(new java.awt.Color(0, 102, 255));
        update.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(610, 500, 90, 31);

        cancel.setBackground(new java.awt.Color(255, 0, 0));
        cancel.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(770, 500, 90, 31);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Images/heineken_beer_bottle_1080p_wallpaper.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel7.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel7.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1460, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
         AdminHome AH = new AdminHome();
        AH.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
         try {
            String sql = "Insert into CUSTOMER (LICENCENUMBER,FIRSTNAME,LASTNAME,ADDRESS) values (?,?,?,?)";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, licencenumber.getText());

            pst.setString(2, firstname.getText());
            pst.setString(3, lastname.getText());

            pst.setString(4, address.getText());
           
            rs = (OracleResultSet) pst.executeQuery();
            JOptionPane.showMessageDialog(null, "Customer Record Saved");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        licencenumber.setText("");
        firstname.setText("");
        lastname.setText("");
        address.setText("");
       
    }//GEN-LAST:event_saveActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        ViewCustomer VC = new ViewCustomer();
        VC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        UpdateCustomer UC = new UpdateCustomer();
        UC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField licencenumber;
    private javax.swing.JButton save;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
