/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Ratnadip
 */
public class Purchase extends javax.swing.JFrame {
java.sql.Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
 
    /**
     * Creates new form Purchase
     */
    public Purchase() {
        initComponents();
        showTime();
        showDate();
         conn = Dbconnect.ConnectDb();
         Fill_Vehicle_Number_Combo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        transportnumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        vehiclenumber = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        district = new javax.swing.JTextField();
        kindoflicence = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        purchasedate = new javax.swing.JTextField();
        showtime = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        brandname = new javax.swing.JComboBox<>();
        strength = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sizeofbottle = new javax.swing.JComboBox<>();
        imflcase = new javax.swing.JComboBox<>();
        batchno = new javax.swing.JTextField();
        mfgdate = new javax.swing.JTextField();
        totalnobottle = new javax.swing.JTextField();
        priceperbottle = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText(" Beer & Wine Shopee");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 20, 640, 60);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Purchase Entry");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 80, 210, 30);

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel3.setText("Transport No:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 160, 120, 30);

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel4.setText("Vehicle No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 110, 100, 30);
        getContentPane().add(transportnumber);
        transportnumber.setBounds(160, 160, 160, 30);

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel5.setText("Name Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 210, 120, 30);
        getContentPane().add(name);
        name.setBounds(160, 210, 160, 30);

        vehiclenumber.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                vehiclenumberPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(vehiclenumber);
        vehiclenumber.setBounds(160, 110, 160, 30);

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel6.setText("District");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 120, 80, 30);

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel7.setText("Kind Of Licence");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 170, 120, 30);

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(350, 220, 90, 30);
        getContentPane().add(district);
        district.setBounds(470, 120, 160, 30);
        getContentPane().add(kindoflicence);
        kindoflicence.setBounds(470, 170, 160, 30);
        getContentPane().add(quantity);
        quantity.setBounds(470, 220, 160, 30);

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel10.setText("Purchase Date");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(710, 120, 120, 30);
        getContentPane().add(purchasedate);
        purchasedate.setBounds(830, 120, 160, 30);

        showtime.setBackground(new java.awt.Color(240, 240, 240));
        showtime.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        getContentPane().add(showtime);
        showtime.setBounds(960, 30, 150, 40);

        date.setBackground(new java.awt.Color(240, 240, 240));
        date.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        getContentPane().add(date);
        date.setBounds(80, 30, 140, 40);

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel9.setText("Name Of Brand");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(710, 180, 110, 20);

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel11.setText("Strength");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(710, 230, 120, 20);

        brandname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kingfisher", "Tuborg", "Heineken", "Knockout", "Carslberg" }));
        getContentPane().add(brandname);
        brandname.setBounds(830, 170, 160, 30);

        strength.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mild", "Strong" }));
        getContentPane().add(strength);
        strength.setBounds(830, 220, 160, 30);

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel12.setText("Size of Bottle");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 270, 100, 20);

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel13.setText("No of IMFL Cases");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 330, 120, 20);

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel14.setText("Batch No");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(350, 280, 80, 20);

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel15.setText("MFG Date");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(350, 340, 80, 20);

        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel16.setText("Total No of Bottle");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(710, 290, 120, 20);

        jLabel17.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel17.setText("Price per Bottle");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(710, 340, 110, 20);

        sizeofbottle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "180", "275", "330", "500", "650", "750", "1000", "1500" }));
        getContentPane().add(sizeofbottle);
        sizeofbottle.setBounds(160, 270, 160, 30);

        imflcase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        getContentPane().add(imflcase);
        imflcase.setBounds(160, 320, 160, 30);
        getContentPane().add(batchno);
        batchno.setBounds(470, 270, 160, 30);
        getContentPane().add(mfgdate);
        mfgdate.setBounds(470, 330, 160, 30);
        getContentPane().add(totalnobottle);
        totalnobottle.setBounds(830, 280, 160, 30);
        getContentPane().add(priceperbottle);
        priceperbottle.setBounds(830, 330, 160, 30);

        jLabel18.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel18.setText("Total");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(350, 420, 50, 20);
        getContentPane().add(total);
        total.setBounds(470, 410, 160, 30);

        savebtn.setBackground(new java.awt.Color(0, 204, 0));
        savebtn.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn);
        savebtn.setBounds(380, 480, 65, 29);

        viewbtn.setBackground(new java.awt.Color(255, 255, 0));
        viewbtn.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        viewbtn.setText("View Purchase");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewbtn);
        viewbtn.setBounds(490, 480, 131, 29);

        cancelbtn.setBackground(new java.awt.Color(255, 0, 0));
        cancelbtn.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelbtn);
        cancelbtn.setBounds(670, 480, 77, 29);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 480, 65, 30);

        jLabel19.setBackground(new java.awt.Color(204, 204, 255));
        jLabel19.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Please fill date in \"YYYY-MM-DD\"");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(460, 370, 190, 17);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Images/corona-extra-beer-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 1420, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // TODO add your handling code here:
        AdminHome AH = new AdminHome();
        AH.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void vehiclenumberPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_vehiclenumberPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
            String tmp = (String) vehiclenumber.getSelectedItem();
        String sql = "select * from TRANSPORTINFO where VEHICLENO=?";
        try {
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs = (OracleResultSet) pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("TRANSPORTNO");
                transportnumber.setText(add1);
                String add2 = rs.getString("NAMEADDRESS");
                name.setText(add2);
                String add3 = rs.getString("DISTRICT");
                district.setText(add3);
                    String add4 = rs.getString("KINDOFLICENCE");
                kindoflicence.setText(add4);
                String add5 = rs.getString("QUANTITY");
                quantity.setText(add5);
               
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        
    }//GEN-LAST:event_vehiclenumberPopupMenuWillBecomeInvisible

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
          try {
            String sql = "Insert into PURCHASE (TRANSPORTNO,NAMEADDRESS,KINDOFLICENCE,VEHICLENO,ISSUEDATE,QUANTITY,DISTRICT,NAMEOFBRAND,STRENGTH,SIZEOFBOTTLE,TOTALNOOFIMFLCASE,BATCHNO,MONTHOFMFG,TOTALNOOFBOTTLE,PERBOTTLEPRICE,TOTAL) values (?,?,?,?,?,?,?,?,?,?,?,?,to_date(?, 'yyyy-mm-dd'),?,?,?)";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            String value=transportnumber.getText();
            pst.setString(1, value);
            pst.setString(2, name.getText());

            pst.setString(3, kindoflicence.getText());
            String val1=vehiclenumber.getSelectedItem().toString();
            pst.setString(4, val1);
            pst.setString(5, purchasedate.getText());
            pst.setString(6, quantity.getText());
            pst.setString(7, district.getText());
            String val =brandname.getSelectedItem().toString();
            pst.setString(8, val);
            String val2 =strength.getSelectedItem().toString();
            pst.setString(9, val2);
            String val3 =sizeofbottle.getSelectedItem().toString();
            pst.setString(10, val3);
            String val4 =imflcase.getSelectedItem().toString();
            pst.setString(11, val4);
            pst.setString(12, batchno.getText());
            pst.setString(13, mfgdate.getText());
            pst.setString(14, totalnobottle.getText());
            pst.setString(15, priceperbottle.getText());
            pst.setString(16, total.getText());

            rs = (OracleResultSet) pst.executeQuery();
            JOptionPane.showMessageDialog(null, "Saved");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        name.setText("");
        kindoflicence.setText("");
        transportnumber.setText("");
        quantity.setText("");
        district.setText("");
        batchno.setText("");
        mfgdate.setText("");
        totalnobottle.setText("");
        priceperbottle.setText("");
        total.setText("");
        
    }//GEN-LAST:event_savebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                total.setText((Integer.parseInt(totalnobottle.getText())*Integer.parseInt(priceperbottle.getText()))+" ");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
        
        ViewPurchase VP = new ViewPurchase();
        VP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField batchno;
    private javax.swing.JComboBox<String> brandname;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JTextField date;
    private javax.swing.JTextField district;
    private javax.swing.JComboBox<String> imflcase;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kindoflicence;
    private javax.swing.JTextField mfgdate;
    private javax.swing.JTextField name;
    private javax.swing.JTextField priceperbottle;
    private javax.swing.JTextField purchasedate;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField showtime;
    private javax.swing.JComboBox<String> sizeofbottle;
    private javax.swing.JComboBox<String> strength;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totalnobottle;
    private javax.swing.JTextField transportnumber;
    private javax.swing.JComboBox<String> vehiclenumber;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables

    private void showTime() {
 
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                showtime.setText(s.format(d));
            }
        }).start();
    }   

    private void showDate() {

        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        date.setText(s.format(d));
        purchasedate.setText(s.format(d));
    }    

    private void Fill_Vehicle_Number_Combo() {
try {
            String sql = "select * from transportinfo";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();

            while (rs.next()) {
                String name = rs.getString("VEHICLENO");
                vehiclenumber.addItem(name);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }       }
}

