/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Ratnadip
 */
public class UpdateStorage extends javax.swing.JFrame {
java.sql.Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
  
    /**
     * Creates new form UpdateStorage
     */
    public UpdateStorage() {
        initComponents();
         conn = Dbconnect.ConnectDb();
                Fill_BatchNo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        barcodeid = new javax.swing.JTextField();
        brand = new javax.swing.JTextField();
        strength = new javax.swing.JTextField();
        size = new javax.swing.JTextField();
        priceperbottle = new javax.swing.JTextField();
        expiry = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        batchno = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        newquantity = new javax.swing.JTextField();
        addstock = new javax.swing.JButton();
        save = new javax.swing.JButton();
        viewstorage = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Beer & Wine Shopee");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 30, 530, 60);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Update Storage");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 100, 140, 20);

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        jLabel3.setText("Select Batch No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 140, 170, 23);

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        jLabel4.setText("Barcode Id");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 190, 140, 23);

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        jLabel5.setText("Name of Brand");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 250, 160, 23);

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        jLabel6.setText("Strength");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 310, 120, 23);

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        jLabel7.setText("Size of Bottle");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 140, 120, 23);

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        jLabel8.setText("Price Per bottle");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 200, 120, 23);

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        jLabel9.setText("Expiry Date");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(520, 260, 120, 23);

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        jLabel10.setText("Available Stock");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(520, 320, 130, 23);
        getContentPane().add(barcodeid);
        barcodeid.setBounds(320, 190, 130, 30);
        getContentPane().add(brand);
        brand.setBounds(320, 250, 130, 30);
        getContentPane().add(strength);
        strength.setBounds(320, 310, 130, 30);
        getContentPane().add(size);
        size.setBounds(700, 140, 160, 30);
        getContentPane().add(priceperbottle);
        priceperbottle.setBounds(700, 200, 160, 30);
        getContentPane().add(expiry);
        expiry.setBounds(700, 260, 160, 30);
        getContentPane().add(quantity);
        quantity.setBounds(700, 320, 160, 30);

        batchno.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                batchnoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(batchno);
        batchno.setBounds(320, 140, 130, 30);

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        jLabel11.setText("Enter Quantity");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(280, 370, 130, 23);
        getContentPane().add(newquantity);
        newquantity.setBounds(460, 370, 130, 30);

        addstock.setBackground(new java.awt.Color(255, 255, 0));
        addstock.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        addstock.setText("Add Stock");
        addstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstockActionPerformed(evt);
            }
        });
        getContentPane().add(addstock);
        addstock.setBounds(150, 490, 120, 30);

        save.setBackground(new java.awt.Color(51, 204, 0));
        save.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(330, 490, 100, 30);

        viewstorage.setBackground(new java.awt.Color(0, 102, 204));
        viewstorage.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        viewstorage.setText("View Storage");
        viewstorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstorageActionPerformed(evt);
            }
        });
        getContentPane().add(viewstorage);
        viewstorage.setBounds(490, 490, 140, 30);

        cancel.setBackground(new java.awt.Color(255, 0, 0));
        cancel.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(670, 490, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batchnoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_batchnoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         String tmp = (String) batchno.getSelectedItem();
        String sql = "select * from storage where BATCHNO=?";
        try {
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs = (OracleResultSet) pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("BRANDNAME");
                brand.setText(add1);
                String add2 = rs.getString("TYPE");
                strength.setText(add2);
                String add3 = rs.getString("SIZEOFLIQUOR");
                size.setText(add3);
                String add4 = rs.getString("BARCODEID");
                barcodeid.setText(add4);
                String add5 = rs.getString("PRICEPERBOTTLE");
                priceperbottle.setText(add5);
                String add6 = rs.getString("QUANTITY");
                quantity.setText(add6);
                String add7 = rs.getString("EXPIRYDATE");
                expiry.setText(add7); 
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();
        }
    }//GEN-LAST:event_batchnoPopupMenuWillBecomeInvisible

    private void addstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstockActionPerformed
        // TODO add your handling code here:
         quantity.setText((Integer.parseInt(newquantity.getText()) + Integer.parseInt(quantity.getText()))+" ");

    }//GEN-LAST:event_addstockActionPerformed

    private void viewstorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstorageActionPerformed
        // TODO add your handling code here:
        ViewStorage VS = new ViewStorage();
        VS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewstorageActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
         AdminHome AH= new AdminHome();
        AH.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
         try {
            String sql = "Update STORAGE set BARCODEID=?,BRANDNAME=?,EXPIRYDATE=?,SIZEOFLIQUOR=?,PRICEPERBOTTLE=?,QUANTITY=?,TYPE=? where BATCHNO=?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, barcodeid.getText());
            pst.setString(2,brand.getText());
           
            pst.setString(3,expiry.getText());
            pst.setString(4,size.getText() );
            pst.setString(5, priceperbottle.getText());
            pst.setString(6,quantity.getText());

            pst.setString(7,strength.getText());
             String value=batchno.getSelectedItem().toString();
            pst.setString(8, value);
            rs = (OracleResultSet) pst.executeQuery();
            JOptionPane.showMessageDialog(null, "Storage Record Updated");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                            e.printStackTrace();

        }  
        barcodeid.setText("");
        brand.setText("");
        size.setText("");
        priceperbottle.setText("");
        quantity.setText("");
        strength.setText("");
        newquantity.setText("");
        expiry.setText("");
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addstock;
    private javax.swing.JTextField barcodeid;
    private javax.swing.JComboBox<String> batchno;
    private javax.swing.JTextField brand;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField expiry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField newquantity;
    private javax.swing.JTextField priceperbottle;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton save;
    private javax.swing.JTextField size;
    private javax.swing.JTextField strength;
    private javax.swing.JButton viewstorage;
    // End of variables declaration//GEN-END:variables

    private void Fill_BatchNo() {
try {
            String sql = "select * from storage";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();

            while (rs.next()) {
                String name = rs.getString("BATCHNO");
                batchno.addItem(name);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }   
    }
}
