/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Ratnadip
 */
public class UpdateTransport extends javax.swing.JFrame {
java.sql.Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
 
    /**
     * Creates new form UpdateTransport
     */
    public UpdateTransport() {
        initComponents();
         conn = Dbconnect.ConnectDb();
         Fill_Vehicle_Number_Combo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vehiclenumber = new javax.swing.JComboBox<>();
        name = new javax.swing.JTextField();
        transportnumber = new javax.swing.JTextField();
        district = new javax.swing.JTextField();
        kindoflicence = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        view = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText(" Beer & Wine Shopee");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 50, 680, 60);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Update Transport Information");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 110, 250, 30);

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel3.setText("Vehicle Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(379, 170, 140, 30);

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel4.setText("Name Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 240, 130, 30);

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel5.setText("Transport Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(382, 310, 150, 30);

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel6.setText("District");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 370, 80, 30);

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel7.setText("Kind of Licence");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(381, 450, 130, 30);

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(381, 530, 90, 30);

        vehiclenumber.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                vehiclenumberPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(vehiclenumber);
        vehiclenumber.setBounds(570, 170, 160, 30);
        getContentPane().add(name);
        name.setBounds(570, 240, 160, 30);
        getContentPane().add(transportnumber);
        transportnumber.setBounds(570, 310, 160, 30);
        getContentPane().add(district);
        district.setBounds(570, 370, 160, 30);
        getContentPane().add(kindoflicence);
        kindoflicence.setBounds(570, 450, 160, 30);
        getContentPane().add(quantity);
        quantity.setBounds(570, 530, 160, 30);

        update.setBackground(new java.awt.Color(0, 153, 0));
        update.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(340, 600, 100, 29);

        view.setBackground(new java.awt.Color(255, 255, 0));
        view.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        view.setText("View Transport");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view);
        view.setBounds(480, 600, 160, 29);

        cancel.setBackground(new java.awt.Color(255, 0, 0));
        cancel.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(680, 600, 100, 29);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Images/budwisertruck.jpg"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel9.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel9.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
         AdminHome AH = new AdminHome();
        AH.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void vehiclenumberPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_vehiclenumberPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         String tmp = (String) vehiclenumber.getSelectedItem();
        String sql = "select * from transportinfo where VEHICLENO=?";
        try {
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs = (OracleResultSet) pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("NAMEADDRESS");
                name.setText(add1);
                String add2 = rs.getString("TRANSPORTNO");
                transportnumber.setText(add2);
                String add3 = rs.getString("DISTRICT");
                district.setText(add3);
                    String add4 = rs.getString("KINDOFLICENCE");
                kindoflicence.setText(add4);
                String add5 = rs.getString("QUANTITY");
                quantity.setText(add5);
               
                

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_vehiclenumberPopupMenuWillBecomeInvisible

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         try{  
                   String sql1 = "UPDATE transportinfo set NAMEADDRESS=?,TRANSPORTNO=?, DISTRICT=?,KINDOFLICENCE=?,QUANTITY=?where VEHICLENO =?";
           pst = (OraclePreparedStatement) conn.prepareStatement(sql1);
            pst.setString(1,name.getText());
                        pst.setString(1,name.getText());
            pst.setString(2,transportnumber.getText());
            pst.setString(3,district.getText());
            pst.setString(4,kindoflicence.getText());
            pst.setString(5,quantity.getText());

            pst.setString(6,vehiclenumber.getSelectedItem().toString());
            rs = (OracleResultSet) pst.executeQuery();
            JOptionPane.showMessageDialog(null, "Transport Vehicle Updated");
               }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);        
        }
         name.setText("");
                  transportnumber.setText("");
         district.setText("");
         kindoflicence.setText("");
         quantity.setText("");
                
         
    }//GEN-LAST:event_updateActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
          ViewTransport VT = new ViewTransport();
        VT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateTransport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField district;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kindoflicence;
    private javax.swing.JTextField name;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField transportnumber;
    private javax.swing.JButton update;
    private javax.swing.JComboBox<String> vehiclenumber;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables

    private void Fill_Vehicle_Number_Combo() {
 try {
            String sql = "select * from transportinfo";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();

            while (rs.next()) {
                String name = rs.getString("VEHICLENO");
                vehiclenumber.addItem(name);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }
}
