/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Ratnadip
 */
public class ViewReport extends javax.swing.JFrame {
java.sql.Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    /**
     * Creates new form ViewReport
     */
    public ViewReport() {
        initComponents();
         conn = Dbconnect.ConnectDb();
         int profit=100;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewbybrand = new javax.swing.JRadioButton();
        viewbysize = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        purchasebrand = new javax.swing.JComboBox<>();
        salesbrand = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        purchasetotal = new javax.swing.JTextField();
        saletotal = new javax.swing.JTextField();
        profit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        purchasesize = new javax.swing.JComboBox<>();
        salesize = new javax.swing.JComboBox<>();
        purchasesizetotal = new javax.swing.JTextField();
        salesizetotal = new javax.swing.JTextField();
        sizeprofit = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        purchasestrengthtotal = new javax.swing.JTextField();
        saletotalstrength = new javax.swing.JTextField();
        purchasestrength = new javax.swing.JComboBox<>();
        salestrength = new javax.swing.JComboBox<>();
        strengthprofit = new javax.swing.JTextField();
        totalpurchasefield = new javax.swing.JTextField();
        totalsalefield = new javax.swing.JTextField();
        totalprofitfield = new javax.swing.JTextField();
        total = new javax.swing.JButton();
        sizetotal = new javax.swing.JButton();
        totalstrength = new javax.swing.JButton();
        saletotalbottle = new javax.swing.JTextField();
        salebottlebtn = new javax.swing.JButton();
        purchasebottlebtn = new javax.swing.JButton();
        purchasebottle = new javax.swing.JTextField();
        sizepurchasebtn = new javax.swing.JButton();
        sizesalebtn = new javax.swing.JButton();
        purchasebottlesize = new javax.swing.JTextField();
        salebottlesize = new javax.swing.JTextField();
        strengthbottlepurchase = new javax.swing.JButton();
        strengthbottlesale = new javax.swing.JButton();
        purchassestrengthbottle = new javax.swing.JTextField();
        salestrengthbottle = new javax.swing.JTextField();
        totalppurchase = new javax.swing.JButton();
        totalsale = new javax.swing.JButton();
        totalprofit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Beer & Wine Shopee");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 30, 480, 50);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel2.setText("Report");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 90, 70, 20);

        viewbybrand.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        viewbybrand.setText("View By Brand");
        viewbybrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbybrandActionPerformed(evt);
            }
        });
        getContentPane().add(viewbybrand);
        viewbybrand.setBounds(80, 140, 160, 29);

        viewbysize.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        viewbysize.setText("View By Size");
        viewbysize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbysizeActionPerformed(evt);
            }
        });
        getContentPane().add(viewbysize);
        viewbysize.setBounds(360, 140, 160, 29);

        jRadioButton3.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jRadioButton3.setText("View By Type");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(680, 140, 160, 29);

        jRadioButton4.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jRadioButton4.setText("View All");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(990, 140, 160, 29);

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel3.setText("Select Purchase Brand");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 200, 150, 17);

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel4.setText("Select Sales Brand");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 260, 130, 17);

        purchasebrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kingfisher", "Tuborg", "Heineken", "Knockout", "Carslberg" }));
        purchasebrand.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                purchasebrandPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(purchasebrand);
        purchasebrand.setBounds(190, 200, 110, 30);

        salesbrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kingfisher", "Tuborg", "Heineken", "Knockout", "Carslberg" }));
        salesbrand.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                salesbrandPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(salesbrand);
        salesbrand.setBounds(190, 260, 110, 30);

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel5.setText("Purchase Total");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 320, 120, 17);

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel6.setText("Sales Total");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 380, 100, 17);

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel7.setText("Profit");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 540, 70, 17);
        getContentPane().add(purchasetotal);
        purchasetotal.setBounds(190, 320, 110, 30);
        getContentPane().add(saletotal);
        saletotal.setBounds(190, 380, 110, 30);
        getContentPane().add(profit);
        profit.setBounds(190, 540, 110, 30);

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel8.setText("Select Purchase Size");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 200, 130, 17);

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel9.setText("Select Sales Size");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 260, 120, 17);

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel10.setText("Purchase Total");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 320, 110, 17);

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel11.setText("Sales Total");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(330, 380, 90, 17);

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel12.setText("Profit");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(330, 550, 60, 17);

        purchasesize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "180", "275", "330", "500", "650", "750", "1000", "1500" }));
        purchasesize.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                purchasesizePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(purchasesize);
        purchasesize.setBounds(520, 190, 110, 30);

        salesize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "180", "275", "330", "500", "650", "750", "1000", "1500" }));
        salesize.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                salesizePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(salesize);
        salesize.setBounds(520, 240, 110, 30);
        getContentPane().add(purchasesizetotal);
        purchasesizetotal.setBounds(520, 310, 110, 30);
        getContentPane().add(salesizetotal);
        salesizetotal.setBounds(520, 370, 110, 30);

        sizeprofit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeprofitActionPerformed(evt);
            }
        });
        getContentPane().add(sizeprofit);
        sizeprofit.setBounds(520, 540, 110, 30);

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel13.setText("Select Purchase Strength");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(650, 200, 140, 20);

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel14.setText("Select Sale Strength");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(650, 250, 120, 20);

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel15.setText("Purchase Total");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(650, 320, 120, 20);

        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel16.setText("Sales Total");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(650, 380, 120, 20);

        jLabel17.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel17.setText("Profit");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(660, 550, 120, 20);
        getContentPane().add(purchasestrengthtotal);
        purchasestrengthtotal.setBounds(816, 320, 100, 30);
        getContentPane().add(saletotalstrength);
        saletotalstrength.setBounds(816, 370, 100, 30);

        purchasestrength.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mild", "Strong" }));
        purchasestrength.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                purchasestrengthPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(purchasestrength);
        purchasestrength.setBounds(826, 200, 90, 30);

        salestrength.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mild", "Strong" }));
        salestrength.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                salestrengthPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(salestrength);
        salestrength.setBounds(826, 250, 90, 30);
        getContentPane().add(strengthprofit);
        strengthprofit.setBounds(816, 550, 100, 30);
        getContentPane().add(totalpurchasefield);
        totalpurchasefield.setBounds(1140, 230, 100, 30);
        getContentPane().add(totalsalefield);
        totalsalefield.setBounds(1140, 300, 100, 30);
        getContentPane().add(totalprofitfield);
        totalprofitfield.setBounds(1140, 370, 100, 30);

        total.setFont(new java.awt.Font("Palatino Linotype", 1, 11)); // NOI18N
        total.setText("Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total);
        total.setBounds(110, 630, 90, 30);

        sizetotal.setFont(new java.awt.Font("Palatino Linotype", 1, 11)); // NOI18N
        sizetotal.setText("Total");
        sizetotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizetotalActionPerformed(evt);
            }
        });
        getContentPane().add(sizetotal);
        sizetotal.setBounds(420, 630, 90, 30);

        totalstrength.setFont(new java.awt.Font("Palatino Linotype", 1, 11)); // NOI18N
        totalstrength.setText("Total");
        totalstrength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalstrengthActionPerformed(evt);
            }
        });
        getContentPane().add(totalstrength);
        totalstrength.setBounds(700, 630, 90, 30);
        getContentPane().add(saletotalbottle);
        saletotalbottle.setBounds(190, 490, 110, 30);

        salebottlebtn.setFont(new java.awt.Font("Palatino Linotype", 1, 11)); // NOI18N
        salebottlebtn.setText("Total Sale Bottle");
        salebottlebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salebottlebtnActionPerformed(evt);
            }
        });
        getContentPane().add(salebottlebtn);
        salebottlebtn.setBounds(30, 490, 150, 20);

        purchasebottlebtn.setFont(new java.awt.Font("Palatino Linotype", 1, 11)); // NOI18N
        purchasebottlebtn.setText("Total Purchase Bottle");
        purchasebottlebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchasebottlebtnActionPerformed(evt);
            }
        });
        getContentPane().add(purchasebottlebtn);
        purchasebottlebtn.setBounds(30, 440, 150, 20);
        getContentPane().add(purchasebottle);
        purchasebottle.setBounds(190, 440, 110, 30);

        sizepurchasebtn.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        sizepurchasebtn.setText("Total Purchase Bottle");
        sizepurchasebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizepurchasebtnActionPerformed(evt);
            }
        });
        getContentPane().add(sizepurchasebtn);
        sizepurchasebtn.setBounds(320, 450, 170, 20);

        sizesalebtn.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        sizesalebtn.setText("Total Sales Bottle");
        sizesalebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizesalebtnActionPerformed(evt);
            }
        });
        getContentPane().add(sizesalebtn);
        sizesalebtn.setBounds(320, 500, 150, 20);

        purchasebottlesize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchasebottlesizeActionPerformed(evt);
            }
        });
        getContentPane().add(purchasebottlesize);
        purchasebottlesize.setBounds(520, 440, 110, 30);
        getContentPane().add(salebottlesize);
        salebottlesize.setBounds(520, 490, 110, 30);

        strengthbottlepurchase.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        strengthbottlepurchase.setText("Total Purchase Bottle");
        strengthbottlepurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strengthbottlepurchaseActionPerformed(evt);
            }
        });
        getContentPane().add(strengthbottlepurchase);
        strengthbottlepurchase.setBounds(650, 450, 150, 20);

        strengthbottlesale.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        strengthbottlesale.setText("Total Sales Bottle");
        strengthbottlesale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strengthbottlesaleActionPerformed(evt);
            }
        });
        getContentPane().add(strengthbottlesale);
        strengthbottlesale.setBounds(650, 500, 150, 20);
        getContentPane().add(purchassestrengthbottle);
        purchassestrengthbottle.setBounds(816, 450, 100, 30);
        getContentPane().add(salestrengthbottle);
        salestrengthbottle.setBounds(816, 500, 100, 30);

        totalppurchase.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        totalppurchase.setText("Total Purchase");
        totalppurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalppurchaseActionPerformed(evt);
            }
        });
        getContentPane().add(totalppurchase);
        totalppurchase.setBounds(980, 230, 120, 25);

        totalsale.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        totalsale.setText("Total Sale");
        totalsale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalsaleActionPerformed(evt);
            }
        });
        getContentPane().add(totalsale);
        totalsale.setBounds(980, 290, 120, 25);

        totalprofit.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        totalprofit.setText("Total Profit");
        totalprofit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalprofitActionPerformed(evt);
            }
        });
        getContentPane().add(totalprofit);
        totalprofit.setBounds(980, 370, 120, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void purchasebrandPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_purchasebrandPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
      
         try {
            String sql;
            sql = ("select sum(total) from purchase  where NAMEOFBRAND='" + (String)purchasebrand.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("sum(total)");
                purchasetotal.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_purchasebrandPopupMenuWillBecomeInvisible

    private void salesbrandPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_salesbrandPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try {
            String sql;
            sql = ("select sum(total) from sales  where BRANDNAME='" + (String)salesbrand.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("sum(total)");
                saletotal.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_salesbrandPopupMenuWillBecomeInvisible

    private void purchasebottlebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasebottlebtnActionPerformed
        // TODO add your handling code here:
         try {
            String sql;
            sql = ("select count(total) from purchase  where nameofbrand='" + (String)purchasebrand.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("count(total)");
                purchasebottle.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_purchasebottlebtnActionPerformed

    private void salebottlebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salebottlebtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql;
            sql = ("select count(total) from sales  where brandname='" + (String)salesbrand.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("count(total)");
                saletotalbottle.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_salebottlebtnActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
                profit.setText((Integer.parseInt(saletotal.getText())- Integer.parseInt(purchasetotal.getText()))+" ");

    }//GEN-LAST:event_totalActionPerformed

    private void purchasebottlesizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasebottlesizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchasebottlesizeActionPerformed

    private void sizeprofitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeprofitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeprofitActionPerformed

    private void purchasesizePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_purchasesizePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         try {
            String sql;
            sql = ("select sum(total) from purchase  where SIZEOFBOTTLE='" + (String)purchasesize.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("sum(total)");
                purchasesizetotal.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_purchasesizePopupMenuWillBecomeInvisible

    private void salesizePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_salesizePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try {
            String sql;
            sql = ("select sum(total) from sales  where SIZEOFLIQUOR='" + (String)salesize.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("sum(total)");
                salesizetotal.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_salesizePopupMenuWillBecomeInvisible

    private void sizepurchasebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizepurchasebtnActionPerformed
        // TODO add your handling code here:
         try {
            String sql;
            sql = ("select count(total) from purchase  where SIZEOFBOTTLE='" + (String)purchasesize.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("count(total)");
                purchasebottlesize.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_sizepurchasebtnActionPerformed

    private void sizesalebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizesalebtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql;
            sql = ("select count(total) from sales  where SIZEOFLIQUOR='" + (String)salesize.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("count(total)");
                salebottlesize.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_sizesalebtnActionPerformed

    private void sizetotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizetotalActionPerformed
        // TODO add your handling code here:
                        sizeprofit.setText((Integer.parseInt(salesizetotal.getText())- Integer.parseInt(purchasesizetotal.getText()))+" ");

    }//GEN-LAST:event_sizetotalActionPerformed

    private void totalstrengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalstrengthActionPerformed
        // TODO add your handling code here:
                                strengthprofit.setText((Integer.parseInt(saletotalstrength.getText())- Integer.parseInt(purchasestrengthtotal.getText()))+" ");

    }//GEN-LAST:event_totalstrengthActionPerformed

    private void purchasestrengthPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_purchasestrengthPopupMenuWillBecomeInvisible
        // TODO add your handling code here
         try {
            String sql;
            sql = ("select sum(total) from purchase  where strength='" + (String)purchasestrength.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("sum(total)");
                purchasestrengthtotal.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_purchasestrengthPopupMenuWillBecomeInvisible

    private void salestrengthPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_salestrengthPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         try {
            String sql;
            sql = ("select sum(total) from sales  where type='" + (String)salestrength.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("sum(total)");
                saletotalstrength.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_salestrengthPopupMenuWillBecomeInvisible

    private void strengthbottlepurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strengthbottlepurchaseActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
         try {
            String sql;
            sql = ("select count(total) from purchase  where strength='" + (String)purchasestrength.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("count(total)");
                purchassestrengthbottle.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_strengthbottlepurchaseActionPerformed

    private void strengthbottlesaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strengthbottlesaleActionPerformed
        // TODO add your handling code here:
         try {
            String sql;
            sql = ("select count(total) from sales  where SIZEOFLIQUOR='" + (String)salestrength.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("count(total)");
                salestrengthbottle.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_strengthbottlesaleActionPerformed

    private void totalppurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalppurchaseActionPerformed
        // TODO add your handling code here:
         try {
            String sql;
            sql = ("select sum(total) from purchase");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("sum(total)");
                totalpurchasefield.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_totalppurchaseActionPerformed

    private void totalsaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalsaleActionPerformed
        // TODO add your handling code here:
         try {
            String sql;
            sql = ("select sum(total) from sales");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
           if (rs.next()) {
                String add1 = rs.getString("sum(total)");
                totalsalefield.setText(add1);
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_totalsaleActionPerformed

    private void totalprofitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalprofitActionPerformed
        // TODO add your handling code here:
                                        totalprofitfield.setText((Integer.parseInt(totalsalefield.getText())- Integer.parseInt(totalpurchasefield.getText()))+" ");

    }//GEN-LAST:event_totalprofitActionPerformed

    private void viewbybrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbybrandActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==viewbybrand){
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
                        jLabel6.setVisible(true);
            purchasebottlebtn.setVisible(true);
            salebottlebtn.setVisible(true);
            total.setVisible(true);
            profit.setVisible(true);
            saletotalbottle.setVisible(true);
            purchasebottle.setVisible(true);
            saletotal.setVisible(true);
            purchasetotal.setVisible(true);
            salesbrand.setVisible(true);
            purchasebrand.setVisible(true);
            
            //view by size
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jLabel11.setVisible(false);
                sizepurchasebtn.setVisible(false);
            sizesalebtn.setVisible(false);
            jLabel12.setVisible(false);
            sizetotal.setVisible(false);
            sizeprofit.setVisible(false);
            salebottlesize.setVisible(false);
            purchasebottlesize.setVisible(false);
            salesizetotal.setVisible(false);
             purchasesizetotal.setVisible(false);
            salesize.setVisible(false);
            purchasesize.setVisible(false);
            
            //view by type
            jLabel13.setVisible(false);
                        jLabel14.setVisible(false);
            jLabel15.setVisible(false);
            jLabel16.setVisible(false);
            strengthbottlepurchase.setVisible(false);
            strengthbottlesale.setVisible(false);
            jLabel17.setVisible(false);
            totalstrength.setVisible(false);
            strengthprofit.setVisible(false);
            salestrengthbottle.setVisible(false);
            purchassestrengthbottle.setVisible(false);
            saletotalstrength.setVisible(false);
            purchasestrengthtotal.setVisible(false);
            salestrength.setVisible(false);
            purchasestrength.setVisible(false);
            
            //view All
            totalppurchase.setVisible(false);
            totalsale.setVisible(false);
            totalprofit.setVisible(false);
            totalprofitfield.setVisible(false);
            totalsalefield.setVisible(false);
            totalpurchasefield.setVisible(false);
           
            
            
        }
    }//GEN-LAST:event_viewbybrandActionPerformed

    private void viewbysizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbysizeActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==viewbysize){
             jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
                        jLabel6.setVisible(false);
            purchasebottlebtn.setVisible(false);
            salebottlebtn.setVisible(false);
            total.setVisible(false);
            profit.setVisible(false);
            saletotalbottle.setVisible(false);
            purchasebottle.setVisible(false);
            saletotal.setVisible(false);
            purchasetotal.setVisible(false);
            salesbrand.setVisible(false);
            purchasebrand.setVisible(false);
             //view by type
            jLabel13.setVisible(false);
                        jLabel14.setVisible(false);
            jLabel15.setVisible(false);
            jLabel16.setVisible(false);
            strengthbottlepurchase.setVisible(false);
            strengthbottlesale.setVisible(false);
            jLabel17.setVisible(false);
            totalstrength.setVisible(false);
            strengthprofit.setVisible(false);
            salestrengthbottle.setVisible(false);
            purchassestrengthbottle.setVisible(false);
            saletotalstrength.setVisible(false);
            purchasestrengthtotal.setVisible(false);
            salestrength.setVisible(false);
            purchasestrength.setVisible(false);
            
            //view All
            totalppurchase.setVisible(false);
            totalsale.setVisible(false);
            totalprofit.setVisible(false);
            totalprofitfield.setVisible(false);
            totalsalefield.setVisible(false);
            totalpurchasefield.setVisible(false);
           
        }
         
           
    }//GEN-LAST:event_viewbysizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField profit;
    private javax.swing.JTextField purchasebottle;
    private javax.swing.JButton purchasebottlebtn;
    private javax.swing.JTextField purchasebottlesize;
    private javax.swing.JComboBox<String> purchasebrand;
    private javax.swing.JComboBox<String> purchasesize;
    private javax.swing.JTextField purchasesizetotal;
    private javax.swing.JComboBox<String> purchasestrength;
    private javax.swing.JTextField purchasestrengthtotal;
    private javax.swing.JTextField purchasetotal;
    private javax.swing.JTextField purchassestrengthbottle;
    private javax.swing.JButton salebottlebtn;
    private javax.swing.JTextField salebottlesize;
    private javax.swing.JComboBox<String> salesbrand;
    private javax.swing.JComboBox<String> salesize;
    private javax.swing.JTextField salesizetotal;
    private javax.swing.JComboBox<String> salestrength;
    private javax.swing.JTextField salestrengthbottle;
    private javax.swing.JTextField saletotal;
    private javax.swing.JTextField saletotalbottle;
    private javax.swing.JTextField saletotalstrength;
    private javax.swing.JTextField sizeprofit;
    private javax.swing.JButton sizepurchasebtn;
    private javax.swing.JButton sizesalebtn;
    private javax.swing.JButton sizetotal;
    private javax.swing.JButton strengthbottlepurchase;
    private javax.swing.JButton strengthbottlesale;
    private javax.swing.JTextField strengthprofit;
    private javax.swing.JButton total;
    private javax.swing.JButton totalppurchase;
    private javax.swing.JButton totalprofit;
    private javax.swing.JTextField totalprofitfield;
    private javax.swing.JTextField totalpurchasefield;
    private javax.swing.JButton totalsale;
    private javax.swing.JTextField totalsalefield;
    private javax.swing.JButton totalstrength;
    private javax.swing.JRadioButton viewbybrand;
    private javax.swing.JRadioButton viewbysize;
    // End of variables declaration//GEN-END:variables
}
