/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Ratnadip
 */
public class ViewPurchase extends javax.swing.JFrame {
java.sql.Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    /**
     * Creates new form ViewPurchase
     */
    public ViewPurchase() {
        initComponents();
        conn = Dbconnect.ConnectDb();
         Fill_Vehicle_Number_Combo();
     //    Fill_Name_Combo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        viewbyname = new javax.swing.JRadioButton();
        viewbysize = new javax.swing.JRadioButton();
        viewbystrength = new javax.swing.JRadioButton();
        viewbyvehicle = new javax.swing.JRadioButton();
        viewall = new javax.swing.JRadioButton();
        brandlbl = new javax.swing.JLabel();
        sizelbl = new javax.swing.JLabel();
        strengthlbl = new javax.swing.JLabel();
        vehiclelbl = new javax.swing.JLabel();
        viewallBtn = new javax.swing.JButton();
        brandcombo = new javax.swing.JComboBox<>();
        sizecombo = new javax.swing.JComboBox<>();
        strengthcombo = new javax.swing.JComboBox<>();
        vehicleviewcombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseinfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText(" Beer & Wine Shopee");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 20, 466, 50);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel2.setText("Purchase Information");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 80, 186, 20);

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel3.setText("View By Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 130, 100, 30);

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel4.setText("View By Size");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 130, 89, 30);

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel5.setText("View By Strength");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(510, 130, 119, 30);

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel6.setText("View By Vehicle");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(760, 130, 111, 30);

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel7.setText("View All");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1010, 130, 60, 30);

        buttonGroup1.add(viewbyname);
        viewbyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbynameActionPerformed(evt);
            }
        });
        getContentPane().add(viewbyname);
        viewbyname.setBounds(241, 130, 40, 30);

        buttonGroup1.add(viewbysize);
        viewbysize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbysizeActionPerformed(evt);
            }
        });
        getContentPane().add(viewbysize);
        viewbysize.setBounds(421, 130, 40, 30);

        buttonGroup1.add(viewbystrength);
        viewbystrength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbystrengthActionPerformed(evt);
            }
        });
        getContentPane().add(viewbystrength);
        viewbystrength.setBounds(671, 130, 40, 30);

        buttonGroup1.add(viewbyvehicle);
        viewbyvehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbyvehicleActionPerformed(evt);
            }
        });
        getContentPane().add(viewbyvehicle);
        viewbyvehicle.setBounds(911, 130, 40, 30);

        buttonGroup1.add(viewall);
        viewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallActionPerformed(evt);
            }
        });
        getContentPane().add(viewall);
        viewall.setBounds(1100, 130, 40, 30);

        brandlbl.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        brandlbl.setText("Select Brand Name");
        getContentPane().add(brandlbl);
        brandlbl.setBounds(70, 180, 140, 30);

        sizelbl.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        sizelbl.setText("Select Size");
        getContentPane().add(sizelbl);
        sizelbl.setBounds(300, 180, 90, 30);

        strengthlbl.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        strengthlbl.setText("Select Strength");
        getContentPane().add(strengthlbl);
        strengthlbl.setBounds(500, 180, 110, 30);

        vehiclelbl.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        vehiclelbl.setText("Select Vehicle No");
        getContentPane().add(vehiclelbl);
        vehiclelbl.setBounds(760, 180, 120, 30);

        viewallBtn.setBackground(new java.awt.Color(51, 204, 0));
        viewallBtn.setText("View All");
        viewallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewallBtn);
        viewallBtn.setBounds(1069, 180, 80, 30);

        brandcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kingfisher", "Tuborg", "Heineken", "Knockout", "Carslberg" }));
        brandcombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                brandcomboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(brandcombo);
        brandcombo.setBounds(200, 180, 90, 30);

        sizecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "180", "275", "330", "500", "650", "750", "1000", "1500" }));
        sizecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizecomboActionPerformed(evt);
            }
        });
        getContentPane().add(sizecombo);
        sizecombo.setBounds(390, 180, 90, 30);

        strengthcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mild", "Strong" }));
        strengthcombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                strengthcomboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(strengthcombo);
        strengthcombo.setBounds(630, 180, 90, 30);

        vehicleviewcombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                vehicleviewcomboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        vehicleviewcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleviewcomboActionPerformed(evt);
            }
        });
        getContentPane().add(vehicleviewcombo);
        vehicleviewcombo.setBounds(900, 180, 90, 30);

        purchaseinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TRANSPORTNO", "NAMEADDRESS", "KINDOFLICENCE", "VEHICLENO", "ISSUEDATE", "QUANTITY", "DISTRICT", "NAMEOFBRAND", "STRENGTH", "SIZEOFBOTTLE", "TOTALNOOFIMFLCASE", "BATCHNO", "MONTHOFMFG", "TOTALNOOFBOTTLE", "PERBOTTLEPRICE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(purchaseinfo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 260, 1250, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewbynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbynameActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==viewbyname){
            brandlbl.setVisible(true);
             brandcombo.setVisible(true);     
            sizelbl.setVisible(false);
            sizecombo.setVisible(false);
            strengthlbl.setVisible(false);
            strengthcombo.setVisible(false);
            vehiclelbl.setVisible(false);
            vehicleviewcombo.setVisible(false);
            viewallBtn.setVisible(false);
        }
    }//GEN-LAST:event_viewbynameActionPerformed

    private void viewbysizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbysizeActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==viewbysize){
            brandlbl.setVisible(false);
             brandcombo.setVisible(false);     
            sizelbl.setVisible(true);
            sizecombo.setVisible(true);
            strengthlbl.setVisible(false);
            strengthcombo.setVisible(false);
            vehiclelbl.setVisible(false);
            vehicleviewcombo.setVisible(false);
            viewallBtn.setVisible(false);
        }
    }//GEN-LAST:event_viewbysizeActionPerformed

    private void viewbystrengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbystrengthActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==viewbystrength){
            brandlbl.setVisible(false);
             brandcombo.setVisible(false);     
            sizelbl.setVisible(false);
            sizecombo.setVisible(false);
            strengthlbl.setVisible(true);
            strengthcombo.setVisible(true);
            vehiclelbl.setVisible(false);
            vehicleviewcombo.setVisible(false);
            viewallBtn.setVisible(false);
        }
    }//GEN-LAST:event_viewbystrengthActionPerformed

    private void viewbyvehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbyvehicleActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==viewbyvehicle){
            brandlbl.setVisible(false);
             brandcombo.setVisible(false);     
            sizelbl.setVisible(false);
            sizecombo.setVisible(false);
            strengthlbl.setVisible(false);
            strengthcombo.setVisible(false);
            vehiclelbl.setVisible(true);
            vehicleviewcombo.setVisible(true);
            viewallBtn.setVisible(false);
        }
    }//GEN-LAST:event_viewbyvehicleActionPerformed

    private void viewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallActionPerformed
        // TODO add your handling code here:
       if(evt.getSource()==viewall){
            brandlbl.setVisible(false);
             brandcombo.setVisible(false);     
            sizelbl.setVisible(false);
            sizecombo.setVisible(false);
            strengthlbl.setVisible(false);
            strengthcombo.setVisible(false);
            vehiclelbl.setVisible(false);
            vehicleviewcombo.setVisible(false);
            viewallBtn.setVisible(true);
        }
    }//GEN-LAST:event_viewallActionPerformed

    private void vehicleviewcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleviewcomboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_vehicleviewcomboActionPerformed

    private void brandcomboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_brandcomboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         try {
            String sql;
            sql = ("select * from purchase  where NAMEOFBRAND='" + (String)brandcombo.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
            purchaseinfo.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_brandcomboPopupMenuWillBecomeInvisible

    private void strengthcomboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_strengthcomboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try {
            String sql;
            sql = ("select * from purchase  where STRENGTH='" + (String)strengthcombo.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
            purchaseinfo.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_strengthcomboPopupMenuWillBecomeInvisible

    private void sizecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizecomboActionPerformed
        // TODO add your handling code here:
         try {
            String sql;
            sql = ("select * from purchase  where SIZEOFBOTTLE='" + (String)sizecombo.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
            purchaseinfo.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_sizecomboActionPerformed

    private void viewallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallBtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql;
            sql = ("select * from purchase");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
            purchaseinfo.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_viewallBtnActionPerformed

    private void vehicleviewcomboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_vehicleviewcomboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         try {
            String sql;
            sql = ("select * from purchase  where VEHICLENO='" + (String)vehicleviewcombo.getSelectedItem()+"'");
            
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
            purchaseinfo.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_vehicleviewcomboPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPurchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brandcombo;
    private javax.swing.JLabel brandlbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable purchaseinfo;
    private javax.swing.JComboBox<String> sizecombo;
    private javax.swing.JLabel sizelbl;
    private javax.swing.JComboBox<String> strengthcombo;
    private javax.swing.JLabel strengthlbl;
    private javax.swing.JLabel vehiclelbl;
    private javax.swing.JComboBox<String> vehicleviewcombo;
    private javax.swing.JRadioButton viewall;
    private javax.swing.JButton viewallBtn;
    private javax.swing.JRadioButton viewbyname;
    private javax.swing.JRadioButton viewbysize;
    private javax.swing.JRadioButton viewbystrength;
    private javax.swing.JRadioButton viewbyvehicle;
    // End of variables declaration//GEN-END:variables

    private void Fill_Vehicle_Number_Combo() {
try {
            String sql = "select * from purchase";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();

            while (rs.next()) {
                String name = rs.getString("VEHICLENO");
                vehicleviewcombo.addItem(name);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }    }

  /*  private void Fill_Name_Combo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/
}
