/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Ratnadip
 */
public class WorkerRegistration extends javax.swing.JFrame {
 java.sql.Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    /**
     * Creates new form WorkerRegistration
     */
    public WorkerRegistration() {
        initComponents();
                conn = Dbconnect.ConnectDb();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstnameText = new javax.swing.JTextField();
        lastnameText = new javax.swing.JTextField();
        usernameText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JTextField();
        WorkerregisterBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText(" Beer & Wine Shopee");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 70, 660, 66);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel2.setText("Worker Registration");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(600, 150, 210, 26);

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 230, 100, 26);

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 300, 100, 26);

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel5.setText("Username");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(520, 360, 100, 26);

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 430, 100, 26);
        getContentPane().add(firstnameText);
        firstnameText.setBounds(700, 220, 180, 30);
        getContentPane().add(lastnameText);
        lastnameText.setBounds(700, 290, 180, 30);
        getContentPane().add(usernameText);
        usernameText.setBounds(700, 360, 180, 30);
        getContentPane().add(PasswordText);
        PasswordText.setBounds(700, 430, 180, 30);

        WorkerregisterBtn.setBackground(new java.awt.Color(0, 153, 0));
        WorkerregisterBtn.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        WorkerregisterBtn.setText("Register Worker");
        WorkerregisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerregisterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(WorkerregisterBtn);
        WorkerregisterBtn.setBounds(640, 510, 210, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Images/corona-extra-beer-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WorkerregisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerregisterBtnActionPerformed
        // TODO add your handling code here:
       try {
            String sql = "Insert into WORKER (FIRSTNAME,LASTNAME,USERNAME,PASSWORD) values (?,?,?,?)";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, firstnameText.getText());

            pst.setString(2, lastnameText.getText());
            pst.setString(3, usernameText.getText());

            pst.setString(4, PasswordText.getText());
            
            rs = (OracleResultSet) pst.executeQuery();
            JOptionPane.showMessageDialog(null, "Saved");
            WorkerLogin WL = new WorkerLogin();
            WL.setVisible(true);
            this.setVisible(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();
        }
        
    }//GEN-LAST:event_WorkerregisterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PasswordText;
    private javax.swing.JButton WorkerregisterBtn;
    private javax.swing.JTextField firstnameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lastnameText;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
