/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Ratnadip
 */
public class WorkerPayment extends javax.swing.JFrame {
java.sql.Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    /**
     * Creates new form WorkerPayment
     */
    public WorkerPayment() {
        initComponents();
               conn = Dbconnect.ConnectDb();
                    Fill_WorkerCombo();
                   showDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        workerFirstName = new javax.swing.JTextField();
        workerLastName = new javax.swing.JTextField();
        workerMobileNumber = new javax.swing.JTextField();
        workerId = new javax.swing.JComboBox<>();
        workerAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        wokerJoinDate = new javax.swing.JTextField();
        workerPost = new javax.swing.JTextField();
        workerSalary = new javax.swing.JTextField();
        workerPaymentIssue = new javax.swing.JTextField();
        workerPaymentdate = new javax.swing.JTextField();
        workerRemainingPayment = new javax.swing.JTextField();
        makePaymentBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        billNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Beer & Wine Shopee");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 50, 650, 66);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Payment Information");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(600, 120, 200, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Worker Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 210, 120, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("First Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 260, 90, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 310, 90, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mobile Number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 360, 110, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 400, 80, 17);
        getContentPane().add(workerFirstName);
        workerFirstName.setBounds(280, 250, 160, 30);
        getContentPane().add(workerLastName);
        workerLastName.setBounds(280, 300, 160, 30);
        getContentPane().add(workerMobileNumber);
        workerMobileNumber.setBounds(280, 350, 160, 30);

        workerId.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                workerIdPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(workerId);
        workerId.setBounds(280, 200, 160, 30);
        getContentPane().add(workerAddress);
        workerAddress.setBounds(280, 400, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Date Of Joining");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 160, 110, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Post");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(520, 210, 90, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Salary ₹ ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(520, 250, 80, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Payment Issue ₹");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(510, 300, 140, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Date of Payment");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(510, 350, 120, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Remaining Payment ₹");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(510, 400, 150, 17);
        getContentPane().add(wokerJoinDate);
        wokerJoinDate.setBounds(670, 160, 160, 30);
        getContentPane().add(workerPost);
        workerPost.setBounds(670, 210, 160, 30);
        getContentPane().add(workerSalary);
        workerSalary.setBounds(670, 250, 160, 30);
        getContentPane().add(workerPaymentIssue);
        workerPaymentIssue.setBounds(670, 300, 160, 30);
        getContentPane().add(workerPaymentdate);
        workerPaymentdate.setBounds(670, 350, 160, 30);
        getContentPane().add(workerRemainingPayment);
        workerRemainingPayment.setBounds(670, 390, 160, 30);

        makePaymentBtn.setBackground(new java.awt.Color(153, 255, 153));
        makePaymentBtn.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        makePaymentBtn.setText("Make Payment");
        makePaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makePaymentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(makePaymentBtn);
        makePaymentBtn.setBounds(190, 480, 150, 31);

        saveBtn.setBackground(new java.awt.Color(0, 204, 0));
        saveBtn.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn);
        saveBtn.setBounds(370, 480, 150, 31);

        viewBtn.setBackground(new java.awt.Color(153, 153, 255));
        viewBtn.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        viewBtn.setText("View Information");
        getContentPane().add(viewBtn);
        viewBtn.setBounds(550, 480, 170, 31);

        cancelBtn.setBackground(new java.awt.Color(255, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        cancelBtn.setText("Cancel");
        getContentPane().add(cancelBtn);
        cancelBtn.setBounds(750, 480, 150, 31);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Bill Number");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(160, 160, 100, 17);

        billNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billNumberActionPerformed(evt);
            }
        });
        getContentPane().add(billNumber);
        billNumber.setBounds(280, 150, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workerIdPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_workerIdPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String tmp = (String) workerId.getSelectedItem();
        String sql = "select * from WAITER where ID=?";
        try {
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs = (OracleResultSet) pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("FIRSTNAME");
                workerFirstName.setText(add1);
                String add2 = rs.getString("LASTNAME");
                workerLastName.setText(add2);
                String add3 = rs.getString("MOBILENO");
                workerMobileNumber.setText(add3);
                    String add4 = rs.getString("ADDRESS");
                workerAddress.setText(add4);
                String add5 = rs.getString("DATEOFJOIN");
                wokerJoinDate.setText(add5);
                String add6 = rs.getString("POST");
                workerPost.setText(add6);
                 String add7 = rs.getString("SALARY");
                workerSalary.setText(add7);
                

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        
    }//GEN-LAST:event_workerIdPopupMenuWillBecomeInvisible

    private void makePaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makePaymentBtnActionPerformed
          workerRemainingPayment.setText((Integer.parseInt(workerSalary.getText()) - Integer.parseInt(workerPaymentIssue.getText()))+" ");
         
        // TODO add your handling code here:
    }//GEN-LAST:event_makePaymentBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
       try {
            String sql = "insert into WORKERPAYMENT (WORKERNUMBER,BILLNUMBER,FIRSTNAME,LASTNAME,MOBILE,ADDRESS,DATEOFJOIN,POST,SALARY,PAYMENTISSUE,DATEOFPAYMENT,REMAININGPAYMENT)\n" +
"values(?,'?','?','?','?','?','to_date(?,'yyyy-mm-dd')','?','?','?','to_date(?,'yyyy-mm-dd')','?')";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(2, billNumber.getText());
                String val=workerId.getSelectedItem().toString();
                pst.setString(1, val);
            pst.setString(3, workerFirstName.getText());
            pst.setString(4, workerLastName.getText());
            pst.setString(5, workerMobileNumber.getText());
            pst.setString(6, workerAddress.getText());
            pst.setString(7, wokerJoinDate.getText());
            pst.setString(8, workerPost.getText());
            pst.setString(9, workerSalary.getText());
            pst.setString(10, workerPaymentIssue.getText());
            pst.setString(11, workerPaymentdate.getText());
            pst.setString(12, workerRemainingPayment.getText());

            rs = (OracleResultSet) pst.executeQuery();
            JOptionPane.showMessageDialog(null, "Saved");
           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();
        } 
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void billNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billNumberActionPerformed
        // TODO add your handling code here:
              
    }//GEN-LAST:event_billNumberActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        try{
            String sql="select count(billnumber)from workerpayment";
                        pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
            if(rs.next()){
                String count=rs.getString("count(billnumber)");
                billNumber.setText(count);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField billNumber;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton makePaymentBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton viewBtn;
    private javax.swing.JTextField wokerJoinDate;
    private javax.swing.JTextField workerAddress;
    private javax.swing.JTextField workerFirstName;
    private javax.swing.JComboBox<String> workerId;
    private javax.swing.JTextField workerLastName;
    private javax.swing.JTextField workerMobileNumber;
    private javax.swing.JTextField workerPaymentIssue;
    private javax.swing.JTextField workerPaymentdate;
    private javax.swing.JTextField workerPost;
    private javax.swing.JTextField workerRemainingPayment;
    private javax.swing.JTextField workerSalary;
    // End of variables declaration//GEN-END:variables

    private void Fill_WorkerCombo() {
        try {
            String sql = "select * from WAITER";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();

            while (rs.next()) {
                String name = rs.getString("ID");
                workerId.addItem(name);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } //To change body of generated methods, choose Tools | Templates.
    }

   private void showDate() {

        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        workerPaymentdate.setText(s.format(d));
       // purchasedate.setText(s.format(d));
    } 
   
}
