/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Ratnadip
 */
public class WorkerLogin extends javax.swing.JFrame {
 java.sql.Connection conn=null;
OraclePreparedStatement pst=null;
OracleResultSet rs=null;
    /**
     * Creates new form WorkerLogin
     */
    public WorkerLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        workerusername = new javax.swing.JTextField();
        workerpassword = new javax.swing.JPasswordField();
        workerLoginbtn = new javax.swing.JButton();
        WorkerCancelbtn = new javax.swing.JButton();
        workerforgotpassword = new javax.swing.JLabel();
        workerRegister = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Beer & Wine Shopee");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 80, 520, 50);

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Worker Login");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(680, 160, 190, 30);

        jLabel4.setBackground(new java.awt.Color(0, 204, 204));
        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(560, 220, 80, 20);

        jLabel5.setBackground(new java.awt.Color(0, 204, 204));
        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 290, 61, 20);
        getContentPane().add(workerusername);
        workerusername.setBounds(719, 220, 150, 30);

        workerpassword.setText("jPasswordField1");
        getContentPane().add(workerpassword);
        workerpassword.setBounds(720, 280, 150, 30);

        workerLoginbtn.setBackground(new java.awt.Color(0, 204, 51));
        workerLoginbtn.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        workerLoginbtn.setText("Login");
        workerLoginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerLoginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(workerLoginbtn);
        workerLoginbtn.setBounds(560, 370, 80, 29);

        WorkerCancelbtn.setBackground(new java.awt.Color(255, 0, 0));
        WorkerCancelbtn.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        WorkerCancelbtn.setText("Cancel");
        WorkerCancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerCancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(WorkerCancelbtn);
        WorkerCancelbtn.setBounds(780, 370, 77, 29);

        workerforgotpassword.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        workerforgotpassword.setForeground(new java.awt.Color(0, 0, 204));
        workerforgotpassword.setText("Forgot Password ?");
        workerforgotpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerforgotpasswordMouseClicked(evt);
            }
        });
        getContentPane().add(workerforgotpassword);
        workerforgotpassword.setBounds(590, 430, 120, 17);

        workerRegister.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        workerRegister.setForeground(new java.awt.Color(0, 102, 0));
        workerRegister.setText("Register");
        workerRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerRegisterMouseClicked(evt);
            }
        });
        getContentPane().add(workerRegister);
        workerRegister.setBounds(730, 430, 110, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Images/cover-beer.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel3.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel3.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 2330, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workerforgotpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerforgotpasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_workerforgotpasswordMouseClicked

    private void workerRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerRegisterMouseClicked
        // TODO add your handling code here:
        WorkerRegistration wr = new WorkerRegistration();
        wr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_workerRegisterMouseClicked

    private void workerLoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerLoginbtnActionPerformed
        // TODO add your handling code here:
         conn = Dbconnect.ConnectDb();
        try{
            String sql ="Select * from ADMIN where USERNAME=? and PASSWORD=?";
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1,workerusername.getText());
             pst.setString(2,workerpassword.getText());
             rs = (OracleResultSet) pst.executeQuery();
             if(rs.next()){
                
                 AdminHome sales= new AdminHome();
                 sales.setVisible(true);
                 this.setVisible(false);
             }
             else{
                JOptionPane.showMessageDialog(null, " Login Failed");
         
             }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_workerLoginbtnActionPerformed

    private void WorkerCancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerCancelbtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_WorkerCancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton WorkerCancelbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton workerLoginbtn;
    private javax.swing.JLabel workerRegister;
    private javax.swing.JLabel workerforgotpassword;
    private javax.swing.JPasswordField workerpassword;
    private javax.swing.JTextField workerusername;
    // End of variables declaration//GEN-END:variables
}
